packages:
  - website
  - bench
  - utils
  - schemas
allowBuilds:
  "@parcel/watcher": false
  ata-validator: false
  esbuild: false
  lefthook: false
  msgpackr-extract: false
  msw: false
  sharp: false
catalog:
  "@oxfmt/binding-linux-x64-gnu": ^0.62.0
  "@standard-schema/spec": ^1.1.0
  "@ttsc/unplugin": "^0.25.0"
  "@types/node": ^26
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.4
  "@vitest/browser-playwright": ^4.1.10
  "@vitest/expect": ^4.1.10
  "@vitest/pretty-format": ^4.1.10
  dedent: ^1.7.2
  "mix-n-matchers": "^2.4.0"
  oxfmt: "^0.62.0"
  playwright: ^1.62.1
  react: ^19.2.8
  react-dom: ^19.2.8
  "rolldown": ^1.2.3
  ttsc: "^0.25.0"
  typescript: 7.0.2
  valibot: ^1.4.2
  vite: ^8.2.1
  vitest: ^4.1.10
overrides:
  "@opentelemetry/api": ^1.9.1
  "@types/node": ^26
  rolldown: ^1.2.3
  vite: "catalog:"
update:
  githubActions: true
