packages:
  - website
  - bench
  - utils
  - schemas

catalog:
  "@ryoppippi/unplugin-typia": ^2.6.5
  "@standard-schema/spec": ^1.1.0
  "@types/node": 25.5.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@typescript/native-preview": 7.0.0-dev.20260312.1
  "@vitest/expect": ^4.1.0
  "@vitest/pretty-format": ^4.1.0
  dedent: ^1.7.2
  playwright: ^1.58.2
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: 6.0.1-rc
  valibot: ^1.2.0
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
