packages:
  - website
  - bench
  - utils
  - schemas

catalog:
  "@ryoppippi/unplugin-typia": ^2.6.5
  "@standard-schema/spec": ^1.1.0
  "@types/node": ^24
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@typescript/native-preview": 7.0.0-dev.20260220.1
  "@vitest/browser-playwright": ^4.0.18
  "@vitest/expect": ^4.0.18
  "@vitest/pretty-format": ^4.0.18
  dedent: ^1.7.1
  playwright: ^1.58.2
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: 6.0.0-beta
  valibot: ^1.2.0
  vite: 8.0.0-beta.14
  vitest: ^4.0.18

updateConfig:
  ignoreDependencies:
    - "@types/node"
