name: Setup environment
description: Setup environment with Node.js, playwright and pnpm

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: "https://registry.npmjs.org"
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Install Playwright browsers
      shell: bash
      run: pnpm dlx playwright install --with-deps

    - name: Build schemas
      shell: bash
      run: pnpm schemas:build
