name: Setup environment
description: Setup environment with Node.js and pnpm, plus building schemas

runs:
  using: composite
  steps:
    - uses: voidzero-dev/setup-vp@v1
      with:
        node-version: "24"
        cache: true

    - name: Install dependencies
      shell: bash
      run: vp install

    - name: Build schemas
      shell: bash
      run: vp run schemas:build
